console.log("you shouldn't be seeing this");document.addEventListener("DOMContentLoaded",()=>{console.log("DOMContentLoaded event fired");const gameContainer=document.getElementById("game-container");const gameFrame=document.getElementById("game-frame");const backArrow=document.getElementById("back-arrow");backArrow.style.display="none";window.loadGame=function(gameUrl){gameFrame.src=gameUrl;gameContainer.style.display="block";backArrow.style.display="block";window.scrollTo({top:gameContainer.offsetTop,behavior:"smooth"})};backArrow.addEventListener("click",(event)=>{event.preventDefault();gameContainer.style.display="none";backArrow.style.display="none";gameFrame.src=""});let loadingTimeout=setTimeout(()=>{console.log("Loading screen shown (page taking longer than 2s to load)");createLoadingScreen()},2000);window.onload=()=>{clearTimeout(loadingTimeout);removeLoadingScreen()}});function createLoadingScreen(){if(document.getElementById("loading-screen"))return;const loadingScreen=document.createElement("div");loadingScreen.id="loading-screen";loadingScreen.innerHTML=`
        <div class="loader"></div>
        <p>Loading GameZone...</p>
        <div class="progress-bar-container">
            <div class="progress-bar"></div>
        </div>
    `;document.body.prepend(loadingScreen);document.body.style.overflow="hidden";let progress=0;const progressBar=document.querySelector(".progress-bar");const interval=setInterval(()=>{progress+=Math.random()*15;progressBar.style.width=`${Math.min(progress, 100)}%`;if(progress>=100){clearInterval(interval);removeLoadingScreen()}},500)}
function removeLoadingScreen(){const loadingScreen=document.getElementById("loading-screen");if(loadingScreen){loadingScreen.style.display="none";document.body.style.overflow="auto"}}
window.alert=function(){};window.confirm=function(){return!1};window.prompt=function(){return null};console.log("Alert, confirm, and prompt functions have been disabled.");function searchGames(){const input=document.getElementById("gameSearch").value.toLowerCase();const gameCards=document.querySelectorAll(".game-card");const sectionLabels=document.querySelectorAll(".section-label");const noResultsMessage=document.getElementById("no-results");let hasResults=!1;if(input){sectionLabels.forEach(label=>(label.style.display="none"));gameCards.forEach(card=>{const title=card.querySelector("h3").textContent.toLowerCase();if(title.includes(input)){card.style.display="block";hasResults=!0}else{card.style.display="none"}});if(!hasResults){if(!noResultsMessage){const message=document.createElement("div");message.id="no-results";message.textContent="Sorry, but we don't seem to have that :(";document.getElementById("games").appendChild(message)}else{noResultsMessage.style.display="block"}}else if(noResultsMessage){noResultsMessage.style.display="none"}}else{sectionLabels.forEach(label=>(label.style.display="block"));gameCards.forEach(card=>(card.style.display="block"));if(noResultsMessage)noResultsMessage.style.display="none"}}
document.addEventListener("DOMContentLoaded",()=>{const backArrow=document.querySelector(".back-arrow");if(backArrow){backArrow.addEventListener("mouseover",()=>{backArrow.style.backgroundColor="#555"});backArrow.addEventListener("mouseout",()=>{backArrow.style.backgroundColor="#333"})}});document.addEventListener("copy",(event)=>event.preventDefault());document.addEventListener("cut",(event)=>event.preventDefault());document.addEventListener("paste",(event)=>event.preventDefault());document.addEventListener("dragstart",(event)=>event.preventDefault());fetch("https://api.ipregistry.co/?key=tryout").then(response=>response.json()).then(data=>{if(data.security.is_proxy||data.security.is_vpn){window.location.replace("https://7s-4a2.pages.dev/blocked.html")}}).catch(err=>console.error("VPN Detection Failed:",err));if(window.location.href.startsWith("view-source:")){window.location.replace("https://7s-4a2.pages.dev/blocked.html")}
if(window.location.href.startsWith("view-source:")){setTimeout(()=>{window.close()},3000)}
